# numpy practice session

In [1]:
#pip install numpy

In [9]:
# import this library in j,notebook
import numpy as np

# Creating an array using numpy

In [3]:
food = np.array(["Pakora", "Samosa", "Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [4]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(price)

3

In [10]:
price[0:3]

array([5, 5, 5])

In [12]:
food[1]

'Samosa'

In [13]:
price.mean()

5.0

In [16]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [19]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# specify
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [21]:
# specific interval
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
# table of 5
np.arange(5, 55, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [24]:
# line space
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
# specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [26]:
# specify your data type
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions

In [34]:
a = np.array([10, 2.3,153,153,151,51,1,1])
a

array([ 10. ,   2.3, 153. , 153. , 151. ,  51. ,   1. ,   1. ])

In [36]:
a.sort()
a

array([  1. ,   1. ,   2.3,  10. ,  51. , 151. , 153. , 153. ])

In [37]:
b = np.array([10.2, 3.4, 25.5, 5])
b

array([10.2,  3.4, 25.5,  5. ])

In [40]:
c = np.concatenate((a,b))
c

array([  1. ,   1. ,   2.3,  10. ,  51. , 151. , 153. , 153. ,  10.2,
         3.4,  25.5,   5. ])

In [41]:
c.sort()
c

array([  1. ,   1. ,   2.3,   3.4,   5. ,  10. ,  10.2,  25.5,  51. ,
       151. , 153. , 153. ])

# 2-D arrays

In [42]:
a = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [52]:
b = np.array([[4, 6, 7, 9, 9], [5, 4, 3, 2, 1]])
b

array([[4, 6, 7, 9, 9],
       [5, 4, 3, 2, 1]])

In [53]:
c = np.concatenate((a,b), axis=0)
c

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [4, 6, 7, 9, 9],
       [5, 4, 3, 2, 1]])

In [57]:
c = np.concatenate((a,b), axis=1)
c

array([[1, 2, 3, 4, 5, 4, 6, 7, 9, 9],
       [5, 4, 3, 2, 1, 5, 4, 3, 2, 1]])

In [63]:
b = np.array([[5, 6, 7], 
             [8, 9, 10],
             [11, 12, 13]]) 
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [59]:
#to check nuber of dimension in a array
b.ndim

2

In [60]:
#Size (Number of elements)
b.size

9

In [61]:
# For Shape
b.shape

(3, 3)

In [10]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
#reshape
b= a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])